### ISSUE TITLE
different result between KernelDensitySJ.jl and R language's bw.SJ function

### ISSUE THREAD

**Issue by kaji331** [rasmushenningsson/KernelDensitySJ.jl#6]
I am looking for a Julia package can give me the bw.SJ function in R. I tried to implement it based the R codes. But this package and my codes neither gave me the same result of R's bw.SJ function.

For example

bw.SJ(1:10)

Thank you for your help!

**Comment by rasmushenningsson** [comment]
`KernelDensitySJ` uses a different algorithm from `bw.SJ` in R to estimate the bandwidth.

To get more similar results, we can increase the precision:
```julia
julia> bwsj(1:10; rtol=1e-6)
2.4379434308236583
```

```R
> bw.SJ(1:10, nb=10000)
[1] 2.437929
```

(The correct answer is `2.437940600694872` - as calculated by a (slower) reference implementation I have in the unit tests.)


The downside of increasing the precision is that will be slower. For larger vectors, I suspect that `rtol=1e-2` or `rtol=1e-3` will be enough.
I should probably change the default `rtol` since it seems to be a bit to high at the moment.


The main difference between the algorithms is that in R, the values are binned, which makes it fast because it can use FFT, but it precision is inevitably lost. In particular, binning is really bad if there are some large outliers.

**Comment by kaji331** [comment]
> `KernelDensitySJ` uses a different algorithm from `bw.SJ` in R to estimate the bandwidth.
> 
> To get more similar results, we can increase the precision:
> 
> ```julia
> julia> bwsj(1:10; rtol=1e-6)
> 2.4379434308236583
> ```
> 
> ```r
> > bw.SJ(1:10, nb=10000)
> [1] 2.437929
> ```
> 
> (The correct answer is `2.437940600694872` - as calculated by a (slower) reference implementation I have in the unit tests.)
> 
> The downside of increasing the precision is that will be slower. For larger vectors, I suspect that `rtol=1e-2` or `rtol=1e-3` will be enough. I should probably change the default `rtol` since it seems to be a bit to high at the moment.
> 
> The main difference between the algorithms is that in R, the values are binned, which makes it fast because it can use FFT, but it precision is inevitably lost. In particular, binning is really bad if there are some large outliers.

Thank you very much for your answer! It helps me a lot!

**Comment by kaji331** [comment]
Thanks very much for your help and explainations!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
